"""Build notebook and Julia script from maintained text sources; never embed stale image HTML."""
import argparse,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def build(export_only=False):
    n=json.loads((ROOT/'src/threebody/notebook_source.json').read_text())
    for c in n['cells']:
        if ''.join(c['source']).startswith('# Diagnostics shared'):
            c['source']=(ROOT/'src/threebody/validation.jl').read_text().splitlines(keepends=True)
    if not export_only:
        (ROOT/'三体问题数值求解.ipynb').write_text(json.dumps(n,ensure_ascii=False,indent=1)+'\n')
    target=ROOT/'tmp/threebody/threebody.jl';target.parent.mkdir(parents=True,exist_ok=True)
    target.write_text('# Generated by scripts/build_threebody.py; edit src/threebody sources.\nENV["GKSwstype"]="100"\n'+'\n\n'.join(''.join(c['source']) for c in n['cells'] if c['cell_type']=='code'))
if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--export-only',action='store_true');build(p.parse_args().export_only)
